idf_component_register(SRCS "src/rplidar_driver.cpp"
                            "src/sl_async_transceiver.cpp"
                            "src/sl_crc.cpp"
                            "src/sl_lidar_driver.cpp"
                            "src/sl_lidarprotocol_codec.cpp"
                            "src/sl_serial_channel.cpp"
                            "src/sl_tcp_channel.cpp"
                            "src/sl_udp_channel.cpp"
                            "src/hal/thread.cpp"
                            "src/dataunpacker/dataunpacker.cpp"
                            "src/dataunpacker/unpacker/handler_capsules.cpp"
                            "src/dataunpacker/unpacker/handler_hqnode.cpp"
                            "src/dataunpacker/unpacker/handler_normalnode.cpp"
                            "src/arch/esp32/net_serial.cpp"
                            "src/arch/esp32/timer.cpp"
                    INCLUDE_DIRS "include" "src"
                    REQUIRES driver)
